apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: web-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: web-nodejs:latest  # Tu imagen de Node.js
        imagePullPolicy: Never
        env:
        - name: DB_HOST
          value: "mysql-service"  # Nombre del servicio MySQL
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: ""  # Contraseña vacía
        - name: DB_DATABASE
          value: "db_products"
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: web-stack
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: LoadBalancer
  loadBalancerIP: 192.168.49.114
