apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: web-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: web-mysql:latest
        imagePullPolicy: Never
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ""
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"  # Permitir contraseña vacía
        - name: MYSQL_DATABASE
          value: "db_products"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: web-stack
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
  type: LoadBalancer
